2019-07-08 17:10:14,381 - root - ERROR - utils  - 170 - BestBuy(5368400)报错信息：url格式不符合要求
Traceback (most recent call last):
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 163, in run
    self.get_url(url)
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 36, in get_url
    self.max_date = max_date(self.sku_id)
  File "C:\Users\hhh\Desktop\Demo\reviews\utils.py", line 126, in max_date
    max_date = c.execute(sql).fetchone()[0]
cx_Oracle.OperationalError: ORA-01013: 用户请求取消当前的操作
2019-07-08 17:10:14,383 - root - ERROR - utils  - 170 - BestBuy(5892993)报错信息：url格式不符合要求
Traceback (most recent call last):
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 163, in run
    self.get_url(url)
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 36, in get_url
    self.max_date = max_date(self.sku_id)
  File "C:\Users\hhh\Desktop\Demo\reviews\utils.py", line 126, in max_date
    max_date = c.execute(sql).fetchone()[0]
cx_Oracle.OperationalError: ORA-03114: 未连接到 ORACLE
2019-07-08 17:10:14,384 - root - ERROR - utils  - 170 - BestBuy(6349969)报错信息：url格式不符合要求
Traceback (most recent call last):
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 163, in run
    self.get_url(url)
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 36, in get_url
    self.max_date = max_date(self.sku_id)
  File "C:\Users\hhh\Desktop\Demo\reviews\utils.py", line 126, in max_date
    max_date = c.execute(sql).fetchone()[0]
cx_Oracle.OperationalError: ORA-03114: 未连接到 ORACLE
2019-07-08 17:11:45,953 - root - ERROR - utils  - 170 - BestBuy(5368400)报错信息：url格式不符合要求
Traceback (most recent call last):
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 163, in run
    self.get_url(url)
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 36, in get_url
    self.max_date = max_date(self.sku_id)
  File "C:\Users\hhh\Desktop\Demo\reviews\utils.py", line 126, in max_date
    max_date = c.execute(sql).fetchone()[0]
cx_Oracle.OperationalError: ORA-12153: TNS: 未连接
2019-07-08 17:11:45,955 - root - ERROR - utils  - 170 - BestBuy(5892993)报错信息：url格式不符合要求
Traceback (most recent call last):
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 163, in run
    self.get_url(url)
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 36, in get_url
    self.max_date = max_date(self.sku_id)
  File "C:\Users\hhh\Desktop\Demo\reviews\utils.py", line 126, in max_date
    max_date = c.execute(sql).fetchone()[0]
cx_Oracle.OperationalError: ORA-03114: 未连接到 ORACLE
2019-07-08 17:11:45,956 - root - ERROR - utils  - 170 - BestBuy(6349969)报错信息：url格式不符合要求
Traceback (most recent call last):
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 163, in run
    self.get_url(url)
  File "C:\Users\hhh\Desktop\Demo\reviews\bestbuy\bestbuy_review.py", line 36, in get_url
    self.max_date = max_date(self.sku_id)
  File "C:\Users\hhh\Desktop\Demo\reviews\utils.py", line 126, in max_date
    max_date = c.execute(sql).fetchone()[0]
cx_Oracle.OperationalError: ORA-03114: 未连接到 ORACLE
