2019-07-04 16:25:36,071 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち4.0'
2019-07-04 16:25:36,074 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち2.0'
2019-07-04 16:25:36,076 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち5.0'
2019-07-04 16:25:36,078 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち5.0'
2019-07-04 16:25:36,080 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち5.0'
2019-07-04 16:25:36,082 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち5.0'
2019-07-04 16:25:36,084 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 140, in comment_data
    re_date = datetime.strptime(dataStr, "%Y/%m/%d")
  File "C:\Users\hhh\AppData\Local\Programs\Python\Python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\hhh\AppData\Local\Programs\Python\Python37\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2019/2/0' does not match format '%Y/%m/%d'
2019-07-04 16:25:36,087 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち5.0'
2019-07-04 16:25:36,089 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち2.0'
2019-07-04 16:25:36,090 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 115, in comment_data
    print(comment_dict['comment_title'])
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f62d' in position 11: illegal multibyte sequence
2019-07-04 16:25:36,982 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち5.0'
2019-07-04 16:25:36,984 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち2.0'
2019-07-04 16:25:36,986 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち4.0'
2019-07-04 16:25:36,988 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 140, in comment_data
    re_date = datetime.strptime(dataStr, "%Y/%m/%d")
  File "C:\Users\hhh\AppData\Local\Programs\Python\Python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\hhh\AppData\Local\Programs\Python\Python37\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2019/3/0' does not match format '%Y/%m/%d'
2019-07-04 16:25:36,990 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち5.0'
2019-07-04 16:25:36,992 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 115, in comment_data
    print(comment_dict['comment_title'])
UnicodeEncodeError: 'gbk' codec can't encode character '\u30fb' in position 11: illegal multibyte sequence
2019-07-04 16:25:36,994 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち1.0'
2019-07-04 16:25:36,996 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち4.0'
2019-07-04 16:25:36,998 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち3.0'
2019-07-04 16:25:37,000 - root - ERROR - utils  - 161 - Amazon(B07N6NRS8Q)报错信息：https://www.amazon.co.jp
Traceback (most recent call last):
  File "C:/Users/hhh/Desktop/Demo/reviews/amazon/amazon_review.py", line 161, in comment_data
    score = float(score)
ValueError: could not convert string to float: '5つ星のうち5.0'
