2019-06-26 10:26:33,324 - root - ERROR - utils  - 148 - tmall(587390513906)报错信息：发送请求,进入评论页面失败
Traceback (most recent call last):
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 186, in run
    self.enter_review()  # 发送请求,进入评论页面
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 52, in enter_review
    self.order_time()
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 91, in order_time
    lambda driver: self.driver.find_elements_by_tag_name('a"'))
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-06-26 10:27:33,564 - root - ERROR - utils  - 148 - tmall(590865770191)报错信息：发送请求,进入评论页面失败
Traceback (most recent call last):
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 186, in run
    self.enter_review()  # 发送请求,进入评论页面
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 52, in enter_review
    self.order_time()
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 91, in order_time
    lambda driver: self.driver.find_elements_by_tag_name('a"'))
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-06-26 10:28:36,986 - root - ERROR - utils  - 148 - tmall(528515320283)报错信息：发送请求,进入评论页面失败
Traceback (most recent call last):
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 186, in run
    self.enter_review()  # 发送请求,进入评论页面
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 52, in enter_review
    self.order_time()
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 91, in order_time
    lambda driver: self.driver.find_elements_by_tag_name('a"'))
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-06-26 10:29:42,512 - root - ERROR - utils  - 148 - tmall(565187422922)报错信息：发送请求,进入评论页面失败
Traceback (most recent call last):
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 186, in run
    self.enter_review()  # 发送请求,进入评论页面
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 52, in enter_review
    self.order_time()
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 91, in order_time
    lambda driver: self.driver.find_elements_by_tag_name('a"'))
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-06-26 10:30:46,307 - root - ERROR - utils  - 148 - tmall(552634156539)报错信息：发送请求,进入评论页面失败
Traceback (most recent call last):
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 186, in run
    self.enter_review()  # 发送请求,进入评论页面
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 52, in enter_review
    self.order_time()
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 91, in order_time
    lambda driver: self.driver.find_elements_by_tag_name('a"'))
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2019-06-26 10:31:50,356 - root - ERROR - utils  - 148 - tmall(580233296207)报错信息：发送请求,进入评论页面失败
Traceback (most recent call last):
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 186, in run
    self.enter_review()  # 发送请求,进入评论页面
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 52, in enter_review
    self.order_time()
  File "C:\Users\BruceChen\Desktop\Demo\reviews\TMALL\tmall_review.py", line 91, in order_time
    lambda driver: self.driver.find_elements_by_tag_name('a"'))
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

