2019-07-03 12:02:36,462 - root - ERROR - utils  - 161 - tmall(528515320283)报错信息：发送请求,进入评论页面失败
Traceback (most recent call last):
  File "C:\Users\hhh\Desktop\Demo\reviews\TMALL\tmall_review.py", line 205, in run
    self.enter_review()  # 发送请求,进入评论页面
  File "C:\Users\hhh\Desktop\Demo\reviews\TMALL\tmall_review.py", line 64, in enter_review
    self.order_time()
  File "C:\Users\hhh\Desktop\Demo\reviews\TMALL\tmall_review.py", line 105, in order_time
    element_artist[1].click()
  File "C:\Users\hhh\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\hhh\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\hhh\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hhh\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=75.0.3770.100)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)

