2019-06-28 11:54:05,822 - root - ERROR - utils  - 153 - tmall(574870586003)报错信息：发送请求,进入评论页面失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/TMALL/tmall_review.py", line 190, in run
    self.enter_review()  # 发送请求,进入评论页面
  File "C:/Users/BruceChen/Desktop/Demo/reviews/TMALL/tmall_review.py", line 54, in enter_review
    self.order_time()
  File "C:/Users/BruceChen/Desktop/Demo/reviews/TMALL/tmall_review.py", line 95, in order_time
    lambda driver: self.driver.find_elements_by_tag_name('a"'))
  File "C:\Python36-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

