2019-06-28 09:39:01,135 - root - ERROR - utils  - 153 - JD(7438547)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:01,151 - root - ERROR - utils  - 153 - JD(7438547)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:01,169 - root - ERROR - utils  - 153 - JD(7438547)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:01,189 - root - ERROR - utils  - 153 - JD(7438547)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:01,196 - root - ERROR - utils  - 153 - JD(7438547)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:24,601 - root - ERROR - utils  - 153 - JD(100002501954)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:24,660 - root - ERROR - utils  - 153 - JD(100002501954)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:24,690 - root - ERROR - utils  - 153 - JD(100002501954)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:24,769 - root - ERROR - utils  - 153 - JD(100002501954)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:24,861 - root - ERROR - utils  - 153 - JD(100002501954)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:24,929 - root - ERROR - utils  - 153 - JD(100002501954)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:24,993 - root - ERROR - utils  - 153 - JD(100002501954)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:39:25,215 - root - ERROR - utils  - 153 - JD(27115314210)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:39:25,215 - root - ERROR - utils  - 153 - JD(27115314210)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:39:42,591 - root - ERROR - utils  - 153 - JD(8031600)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:39:42,591 - root - ERROR - utils  - 153 - JD(8031600)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:40:00,330 - root - ERROR - utils  - 153 - JD(100001470134)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:40:00,330 - root - ERROR - utils  - 153 - JD(100001470134)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:40:19,595 - root - ERROR - utils  - 153 - JD(34326476497)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:40:19,595 - root - ERROR - utils  - 153 - JD(34326476497)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:40:37,496 - root - ERROR - utils  - 153 - JD(100001667527)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:40:37,496 - root - ERROR - utils  - 153 - JD(100001667527)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:40:56,554 - root - ERROR - utils  - 153 - JD(7224868)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:40:56,555 - root - ERROR - utils  - 153 - JD(7224868)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
